spring:
    jwt:
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK

    datasource:
        url: jdbc:mysql://db-ll12-backend.clcmmk2ygw1j.ap-northeast-2.rds.amazonaws.com:3306/LL12_Backend
        username: root
        password: 20-72008672
        driver-class-name: com.mysql.cj.jdbc.Driver

    mybatis:
      mapper-locations: classpath:mappers/**/*.xml
      configuration:
        map-underscore-to-camel-case: true
    server:
      port: 8081

    jpa:
      properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            hbm2ddl.auto: update
        show-sql: true

    security:
      oauth2:
        client:
          registration:
            google:
              client-id: 892576401029-ipn0tn0bqq7n1mriqhuh107p021s8tdf.apps.googleusercontent.com
              client-secret: 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
              scope:
                - email
                - profile
            kakao:
              client-id: d1e19397c61c9de98802bd1d35363d98
              client-secret: uIJqfZOWt5qSOlohpOaMOb6i2HmwAI5a
              scope:
                - profile_nickname
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8080/login/oauth2/code/kakao
              client-name: Kakao
              client-authentication-method: client_secret_post

            naver:
              client-id: Mmq4Cdt8I_eNRk9Or0rq
              client-secret: rcVose1g1s
              scope:
                - name
                - email
              client-name: Naver
              authorization-grant-type: authorization_code
              redirect-uri: http://localhost:8080/login/oauth2/code/naver

          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
            naver:
              authorization-uri: https://nid.naver.com/oauth2.0/authorize
              token-uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user-name-attribute: response